---
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/mm7/scripts/smokeping/smokeping/config:/config
      - /home/mm7/scripts/smokeping/smokeping/data:/data
    ports:
      - 80:80
    dns:
      - 192.168.1.1  # Speedport DNS
      - 8.8.8.8      # Google DNS
      - 1.1.1.1      # Cloudflare DNS
      - "2001:4860:4860::8888"  # IPv6 Google DNS
    networks:
      - my_ipv6_network
    restart: unless-stopped

networks:
  my_ipv6_network:
    driver: bridge
    enable_ipv6: true
